stages:
  - name: preprocess
    notebooks:
      in:
        module: common
        path: preprocess_submissions.ipynb
      out:
        path: 20210902_preprocess_submissions.ipynb
    values:
      state_name: Missouri
      crs: EPSG:32615  # https://spatialreference.org/ref/epsg/wgs-84-utm-zone-15n/
      ids_url: https://k61e3cz2ni.execute-api.us-east-2.amazonaws.com/prod/submissions/districtr-ids/missouri
      csv_url: https://k61e3cz2ni.execute-api.us-east-2.amazonaws.com/prod/submissions/csv/missouri
      output_path: mo_submissions_20210902.csv  # in MO data directory
      exclude_prefixes: []
    artifacts:
      - id: annotations_20210815
        param: labels_path
      - id: block_relationship
        param: block_2010_to_block_2020_crosswalk_path
      - id: bg_shapefile_2010
        param: bg_2010_shapefile_path
  - name: generate_clusters
    notebooks:
      in:
        module: common
        path: generate_geo_clusters.ipynb
      out:
        path: 20210902_generate_geo_clusters.ipynb
    values:
      distance_save_path: mo_dual_dist.txt  # -> outputs
      db_file_path: mo_cluster_db_20210902.pkl  # -> data
    artifacts:
      - id: bg_2010_graph
        param: dual_graph_path
      - id: submissions_20210902
        param: submissions_path
  - name: generate_outputs
    notebooks:
      in:
        module: common
        path: generate_cluster_outputs.ipynb
      out:
        path: 20210902_cluster_outputs.ipynb
    values:
      num_clusters: 35
      state_fips_code: '29'
      cluster_name_prefix: B  # Moon's versioning scheme
      output_prefix: MO_20210902_geo
      crs: EPSG:32615
      force_connected: false
      swap_area_columns: false
      output_formats:
        - shapefile
        - csv_geo
        - csv_comments
        - html
        - png
        - tex
    artifacts:
      - id: cluster_db_20210902
        param: db_path
      - id: block_relationship
        param: block_2010_to_block_2020_crosswalk_path
      - id: block_2020_shapefile
        param: block_2020_shp_path
      - id: county_shapefile
        module: common
        param: base_shp_path
